"""
This type stub file was generated by pyright.
"""

from .llama import FastLlamaModel
from .loader import FastLanguageModel, FastModel, FastTextModel, FastVisionModel
from .mistral import FastMistralModel
from .qwen2 import FastQwen2Model
from .qwen3 import FastQwen3Model
from .qwen3_moe import FastQwen3MoeModel
from .granite import FastGraniteModel
from .falcon_h1 import FastFalconH1Model
from .dpo import PatchDPOTrainer, PatchKTOTrainer
from ._utils import __version__, is_bfloat16_supported, is_vLLM_available
from .rl import PatchFastRL, vLLMSamplingParams

