"""
This type stub file was generated by pyright.
"""

import os
from .cross_entropy_loss import fast_cross_entropy_loss, patch_loss_functions, post_patch_loss_function
from .rms_layernorm import fast_rms_layernorm, patch_rms_layernorm, unpatch_rms_layernorm
from .layernorm import fast_layernorm, patch_layernorm
from .rope_embedding import fast_rope_embedding, inplace_rope_embedding
from .swiglu import swiglu_DWf_DW_dfg_kernel, swiglu_fg_kernel
from .geglu import geglu_approx_backward_kernel, geglu_approx_forward_kernel, geglu_exact_backward_kernel, geglu_exact_forward_kernel
from .fast_lora import apply_lora_mlp_geglu_approx, apply_lora_mlp_geglu_exact, apply_lora_mlp_swiglu, apply_lora_o, apply_lora_qkv, fast_lora_forward, get_lora_parameters, get_lora_parameters_bias
from .fp8 import *
from .utils import QUANT_STATE, fast_dequantize, fast_gemv, fast_linear_forward, matmul_lora
from .flex_attention import HAS_FLEX_ATTENTION, create_flex_attention_causal_mask, create_flex_attention_sliding_window_mask, slow_attention_softcapping, slow_inference_attention_softcapping

if "UNSLOTH_ZOO_IS_PRESENT" not in os.environ:
    ...
