"""
This type stub file was generated by pyright.
"""

import torch
from .utils import MAX_FUSED_SIZE
from packaging.version import Version

_cross_entropy_forward = ...
_cross_entropy_forward = ...
_chunked_cross_entropy_forward = ...
_chunked_cross_entropy_forward = ...
_cross_entropy_backward = ...
_cross_entropy_backward = ...
MAX_FUSED_SIZE = ...
class Fast_CrossEntropyLoss(torch.autograd.Function):
    @staticmethod
    def forward(ctx, logits, labels, logit_softcapping: float = ..., logit_scaling: float = ...): # -> Tensor:
        ...
    
    @staticmethod
    def backward(ctx, dlosses): # -> tuple[Any, None, None, None]:
        ...
    


def fast_cross_entropy_loss(logits, labels, logit_softcapping=..., logit_scaling=..., n_items=...): # -> Any:
    """
    Arguments:
        logits: (batch, seq_len, vocab_size)
        labels: (batch, seq_len,)
    Returns:
        losses: float
    """
    ...

if (Version(torch.__version__) < Version("2.4.0")) and not hasattr(fast_cross_entropy_loss, "__wrapped__"):
    fast_cross_entropy_loss = ...
def patch_loss_functions(torch_compile=...): # -> None:
    ...

