"""
This type stub file was generated by pyright.
"""

import triton
import triton.language as tl
import torch

@triton.jit
def layernorm_forward(Y, Y_row_stride, X, X_row_stride, W, b, r, mu, n_cols: tl.constexpr, eps: tl.constexpr, BLOCK_SIZE: tl.constexpr):
    ...

@triton.jit
def layernorm_backward(dY, dY_row_stride, X, X_row_stride, W, b, r, mu, n_cols: tl.constexpr, eps: tl.constexpr, BLOCK_SIZE: tl.constexpr):
    ...

class Fast_Layernorm(torch.autograd.Function):
    @staticmethod
    def forward(ctx, X, W, b, eps): # -> Tensor:
        ...
    
    @staticmethod
    def backward(ctx, dY): # -> tuple[Any, None, None, None, None]:
        ...
    


def fast_layernorm(layernorm, X): # -> Any | None:
    ...

def test_layernorm(dim=..., eps=..., dtype=..., bsz=..., random_state=..., seqlen=...): # -> None:
    ...

def testing_suite_layernorm(): # -> None:
    ...

