"""
This type stub file was generated by pyright.
"""

import torch
from transformers.models.llama.modeling_llama import LlamaRMSNorm
from transformers.models.mllama.modeling_mllama import MllamaTextRMSNorm

_rms_layernorm_backward = ...
_rms_layernorm_backward = ...
class Fast_RMS_Layernorm(torch.autograd.Function):
    @staticmethod
    def forward(ctx, X: torch.Tensor, W: torch.Tensor, eps: float, gemma: bool = ...): # -> Tensor:
        ...
    
    @staticmethod
    def backward(ctx, dY: torch.Tensor): # -> tuple[Tensor, None, None, None]:
        ...
    


@torch.compiler.disable
def fast_rms_layernorm(layernorm, X: torch.Tensor, gemma: bool = ...): # -> Any | None:
    ...

class Unsloth_LlamaRMSNorm(LlamaRMSNorm):
    def forward(self, X): # -> Any:
        ...
    


class Unsloth_MllamaTextRMSNorm(MllamaTextRMSNorm):
    def forward(self, X): # -> Any:
        ...
    


def patch_rms_layernorm(): # -> None:
    ...

def unpatch_rms_layernorm(): # -> None:
    ...

def test_rms_layernorm(dim=..., eps=..., dtype=..., bsz=..., random_state=..., seqlen=...): # -> None:
    ...

def testing_suite_layernorm(): # -> None:
    ...

