"""
This type stub file was generated by pyright.
"""

import torch

ROPE_GROUP_SIZE: int = ...
_rope_embedding = ...
_rope_embedding = ...
class Fast_RoPE_Embedding(torch.autograd.Function):
    @staticmethod
    def forward(ctx, Q, cos, sin):
        ...
    
    @staticmethod
    def backward(ctx, dY): # -> tuple[Any, None, None]:
        ...
    


@torch.compiler.disable
def fast_rope_embedding(Q, K, cos, sin): # -> tuple[Any, Any]:
    ...

class Slow_RoPE_Embedding(torch.autograd.Function):
    @staticmethod
    def forward(ctx, Q, cos, sin, position_ids):
        ...
    
    @staticmethod
    def backward(ctx, dY): # -> tuple[Any, None, None, None]:
        ...
    


def inplace_rope_embedding(Q, K, cos, sin, position_ids): # -> tuple[Any | None, Any | None]:
    ...

