"""
This type stub file was generated by pyright.
"""

import subprocess

__all__ = ["SyntheticDataKit"]
def terminate_tree(proc: subprocess.Popen, timeout=...): # -> None:
    ...

class PipeCapture:
    """Non blocking pipe capture"""
    def __init__(self, pipe, keep_lines=..., echo=..., name=..., text=..., encoding=..., errors=..., ready_regex=...) -> None:
        ...
    
    def wait_for_ready(self, timeout=...): # -> bool:
        ...
    
    def has_closed(self): # -> bool:
        ...
    
    def wait_until_closed(self, timeout=...): # -> bool:
        ...
    
    def tail(self, n=...): # -> LiteralString:
        ...
    


class SyntheticDataKit:
    def __init__(self, model_name=..., max_seq_length=..., gpu_memory_utilization=..., float8_kv_cache=..., conservativeness=..., token=..., timeout=..., **kwargs) -> None:
        ...
    
    @staticmethod
    def from_pretrained(model_name=..., max_seq_length=..., gpu_memory_utilization=..., float8_kv_cache=..., conservativeness=..., token=..., **kwargs): # -> SyntheticDataKit:
        ...
    
    @staticmethod
    def check_vllm_status(): # -> bool | None:
        ...
    
    def cleanup(self): # -> None:
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, *exc): # -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def chunk_data(self, filename=...): # -> list[Any]:
        ...
    
    def prepare_qa_generation(self, output_folder=..., max_generation_tokens=..., temperature=..., top_p=..., overlap=..., default_num_pairs=..., cleanup_threshold=..., cleanup_batch_size=..., cleanup_temperature=...): # -> None:
        ...
    


