"""
This type stub file was generated by pyright.
"""

from unsloth.registry.registry import ModelInfo

_IS_QWEN_2_5_REGISTERED = ...
_IS_QWEN_2_5_VL_REGISTERED = ...
_IS_QWEN_QWQ_REGISTERED = ...
class QwenModelInfo(ModelInfo):
    @classmethod
    def construct_model_name(cls, base_name, version, size, quant_type, instruct_tag): # -> str:
        ...
    


class QwenVLModelInfo(ModelInfo):
    @classmethod
    def construct_model_name(cls, base_name, version, size, quant_type, instruct_tag): # -> str:
        ...
    


class QwenQwQModelInfo(ModelInfo):
    @classmethod
    def construct_model_name(cls, base_name, version, size, quant_type, instruct_tag): # -> str:
        ...
    


class QwenQVQPreviewModelInfo(ModelInfo):
    @classmethod
    def construct_model_name(cls, base_name, version, size, quant_type, instruct_tag): # -> str:
        ...
    


Qwen_2_5_Meta = ...
Qwen_2_5_VLMeta = ...
QwenQwQMeta = ...
QwenQVQPreviewMeta = ...
def register_qwen_2_5_models(include_original_model: bool = ...): # -> None:
    ...

def register_qwen_2_5_vl_models(include_original_model: bool = ...): # -> None:
    ...

def register_qwen_qwq_models(include_original_model: bool = ...): # -> None:
    ...

def register_qwen_models(include_original_model: bool = ...): # -> None:
    ...

if __name__ == "__main__":
    ...
