"""
This type stub file was generated by pyright.
"""

from huggingface_hub import HfApi, ModelInfo

_HFAPI: HfApi = ...
POPULARITY_PROPERTIES = ...
THOUSAND = ...
MILLION = ...
BILLION = ...
def formatted_int(value: int) -> str:
    ...

def get_model_info(model_id: str, properties: list[str] = ...) -> ModelInfo:
    """
    Get the model info for a specific model.

    properties: list[str] = See https://huggingface.co/docs/huggingface_hub/api-ref/hf_hub/hf_api/model_info
    Default properties: ["safetensors", "lastModified"], only retrieves minimal information.
    Set to None to retrieve the full model information.
    """
    ...

def list_models(properties: list[str] = ..., full: bool = ..., sort: str = ..., author: str = ..., search: str = ..., limit: int = ...) -> list[ModelInfo]:
    """
    Retrieve model information from the Hugging Face Hub.

    properties: list[str] = See https://huggingface.co/docs/huggingface_hub/api-ref/hf_hub/hf_api/list_models
    full: bool = Whether to retrieve the full model information, if True properties will be ignored.
    sort: str = The sort order.
    author: str = The author of the model.
    search: str = The search query for filtering models.

    """
    ...

