"""
This type stub file was generated by pyright.
"""

import warnings
import importlib
import sys
import os
import re
import subprocess
import inspect
import functools
import numpy as np
import unsloth_zoo
import torch
import triton
import bitsandbytes as bnb
from packaging.version import Version
from .import_fixes import fix_message_factory_issue, fix_vllm_aimv2_issue, fix_xformers_performance_issue, ignore_logger_messages, patch_datasets, patch_ipykernel_hf_xet, patch_trackio
from importlib.metadata import PackageNotFoundError, version as importlib_version
from unsloth_zoo.device_type import ALLOW_PREQUANTIZED_MODELS, DEVICE_COUNT, DEVICE_TYPE, DEVICE_TYPE_TORCH, get_device_type, is_hip
from .models import *
from .models import __version__
from .save import *
from .chat_templates import *
from .tokenizer_utils import *
from .trainer import *
from unsloth_zoo.rl_environments import Benchmarker, check_python_modules, create_locked_down_function, execute_with_time_limit, is_port_open, launch_openenv

critical_modules = ...
already_imported = ...
if already_imported:
    ...
unsloth_zoo_version = ...
if Version(unsloth_zoo_version) < Version("2025.11.2"):
    ...
if DEVICE_TYPE == "cuda":
    SUPPORTS_BFLOAT16 = ...
    old_is_bf16_supported = ...
else:
    SUPPORTS_BFLOAT16 = ...
if DEVICE_TYPE == "cuda":
    libcuda_dirs = ...
    cdequantize_blockwise_fp32 = ...
else:
    ...
