"""
This type stub file was generated by pyright.
"""

import logging

UNSLOTH_ENABLE_LOGGING = ...
class HideLoggingMessage(logging.Filter):
    __slots__ = ...
    def __init__(self, text) -> None:
        ...
    
    def filter(self, x): # -> bool:
        ...
    


def fix_message_factory_issue(): # -> None:
    class MessageFactory:
        ...
    
    

def fix_xformers_performance_issue(): # -> None:
    ...

def fix_vllm_aimv2_issue(): # -> None:
    ...

def ignore_logger_messages(): # -> None:
    ...

def patch_ipykernel_hf_xet(): # -> None:
    ...

def patch_trackio(): # -> None:
    ...

def patch_datasets(): # -> None:
    ...

