"""
This type stub file was generated by pyright.
"""

from trl import SFTConfig as TrainingArguments, SFTTrainer
from packaging.version import Version
from transformers import __version__ as transformers_version

__all__ = ["UnslothTrainingArguments", "UnslothTrainer", "unsloth_train", "_patch_trl_trainer", "UnslothVisionDataCollator"]
if Version(transformers_version) > Version("4.45.2"):
    def unsloth_train(trainer, *args, **kwargs):
        ...
    
else:
    def unsloth_train(trainer, *args, **kwargs): # -> Trainer_Stats:
        ...
    
class UnslothTrainingArguments(TrainingArguments):
    def __init__(self, embedding_learning_rate: float = ..., *args, **kwargs) -> None:
        ...
    


class UnslothTrainer(SFTTrainer):
    def create_optimizer(self): # -> Optimizer | Any | DummyOptim:
        ...
    


